import { useRef, useState } from "react";
import type { Task, Group, AgentType, Priority, ProjectView, DebateStyle } from "@harness/shared";
import { X, ArrowsOut, ArrowsIn, Robot, Stack, Plus, Sparkle, Scales, Handshake } from "@phosphor-icons/react";
import { api } from "./api";
import { PRIORITIES } from "./constants";
import { PriorityIcon, LabelAdder, RunLocation } from "./ui";
import { groupLabel } from "./util";
import { useEscape } from "./useEscape";
import { Pill } from "./Menu";

const AGENTS: AgentType[] = ["claude", "codex", "antigravity"];

// The /pair slash command expands to a style choice right under the typed text.
const PAIR_STYLES: { key: DebateStyle; label: string; hint: string }[] = [
  { key: "debate", label: "辩论", hint: "两个 AI 对抗，给你答案" },
  { key: "collaborate", label: "协作", hint: "一方实现、一方审查，给你代码" },
];

// New-task composer. No title field — the title is auto-generated by the first
// executing agent (user can edit later). Typing `/debate` opens the debate flow.
export function CreateTask({
  project,
  groups,
  onClose,
  onCreated,
  onDebate,
  onCreateGroup,
}: {
  project: ProjectView;
  groups: Group[];
  onClose: () => void;
  onCreated: (t: Task) => void;
  onDebate: (style: DebateStyle) => void;
  onCreateGroup: () => void;
}) {
  const projectId = project.id;
  useEscape(onClose);
  const [body, setBody] = useState("");
  const [priority, setPriority] = useState<Priority>("none");
  const [agentType, setAgentType] = useState<AgentType>("claude");
  const [groupId, setGroupId] = useState("");
  const [labels, setLabels] = useState<string[]>([]);
  const [more, setMore] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [busy, setBusy] = useState(false);
  const [slashIdx, setSlashIdx] = useState(0); // highlighted style in the /pair picker
  const objRef = useRef<HTMLTextAreaElement>(null);

  // Slash command: when the input is just a "/word" token, expand /pair into a
  //辩论/协作 picker right under the text (↑↓ to move, Enter/click to choose).
  const slashMatch = /^\s*\/(\w*)$/.exec(body);
  const slashOpen = !!slashMatch && "pair".startsWith((slashMatch[1] ?? "").toLowerCase());

  const triggerPair = (style: DebateStyle) => {
    setBody("");
    setSlashIdx(0);
    onDebate(style);
  };

  const submit = async () => {
    const obj = body.trim();
    if (!obj || busy) return;
    if (/^\/pair\b/i.test(obj) || slashOpen) {
      triggerPair(PAIR_STYLES[slashIdx].key);
      return;
    }
    setBusy(true);
    try {
      const provisionalTitle = obj.split("\n")[0].slice(0, 30) || "未命名任务";
      const t = await api.createTask({
        projectId,
        title: provisionalTitle,
        body: obj,
        mode: "single",
        agentType,
        priority,
        labels,
        autoTitle: true,
      });
      onCreated(t);
      if (more) {
        setBody("");
        setLabels([]);
        objRef.current?.focus();
      } else {
        onClose();
      }
    } finally {
      setBusy(false);
    }
  };

  const selectedGroup = groups.find((g) => g.id === groupId);
  const groupTrigger = selectedGroup ? groupLabel(selectedGroup) : "分组";
  const prioLabel = priority === "none" ? "优先级" : PRIORITIES.find((p) => p.key === priority)!.label;

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/30 pt-[12vh]" onClick={onClose}>
      <div
        className={`flex flex-col overflow-visible rounded-xl border border-line2 bg-panel shadow-2xl transition-all ${
          expanded ? "h-[78vh] w-[920px]" : "w-[640px]"
        } max-w-[94vw]`}
        onClick={(e) => e.stopPropagation()}
        onKeyDown={(e) => {
          if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
            e.preventDefault();
            submit();
          }
        }}
      >
        {/* Header / breadcrumb */}
        <div className="flex items-center gap-2 px-4 pt-3.5">
          <span className="inline-flex items-center gap-1.5 rounded-md bg-raised px-1.5 py-0.5 text-[12px] font-medium text-ink">
            <span className="grid h-4 w-4 place-items-center rounded bg-accent text-[9px] font-semibold text-accent-fg">
              {project.name.slice(0, 1).toUpperCase()}
            </span>
            {project.name}
          </span>
          <span className="text-faint">›</span>
          <span className="text-[13px] font-medium text-muted">新建任务</span>
          <div className="ml-auto flex items-center gap-1">
            <button onClick={() => setExpanded((v) => !v)} className="grid h-7 w-7 place-items-center rounded-md text-muted hover:bg-raised hover:text-ink" title={expanded ? "收起" : "展开"}>
              {expanded ? <ArrowsIn size={15} /> : <ArrowsOut size={15} />}
            </button>
            <button onClick={onClose} className="grid h-7 w-7 place-items-center rounded-md text-muted hover:bg-raised hover:text-ink" title="关闭 Esc">
              <X size={16} />
            </button>
          </div>
        </div>
        {/* Run location — agents run in this dir (or a temp dir if it's missing) */}
        <div className="px-4 pt-1.5">
          <RunLocation project={project} />
        </div>

        {/* Objective (no title field — AI titles it) */}
        <div className={`relative flex min-h-0 flex-col px-4 pt-3 ${expanded ? "flex-1" : ""}`}>
          <textarea
            ref={objRef}
            autoFocus
            value={body}
            onChange={(e) => setBody(e.target.value)}
            onKeyDown={(e) => {
              if (slashOpen) {
                if (e.key === "ArrowDown") {
                  e.preventDefault();
                  setSlashIdx((i) => Math.min(PAIR_STYLES.length - 1, i + 1));
                } else if (e.key === "ArrowUp") {
                  e.preventDefault();
                  setSlashIdx((i) => Math.max(0, i - 1));
                } else if (e.key === "Enter") {
                  e.preventDefault();
                  triggerPair(PAIR_STYLES[slashIdx].key);
                }
              }
            }}
            placeholder="描述要做什么 / 给 agent 的目标…（输入 / 唤起命令，/pair = 双 AI）"
            className={`resize-none bg-transparent text-[15px] leading-relaxed text-ink outline-none placeholder:text-faint ${
              expanded ? "flex-1" : "min-h-[88px]"
            }`}
          />
          <div className="flex items-center gap-1 pb-1 text-[11px] text-faint">
            <Sparkle size={12} weight="fill" className="text-accent/70" />
            标题将由首个执行的 agent 自动生成，可随后修改
          </div>

          {slashOpen && (
            <div className="absolute left-4 top-9 z-10 w-72 overflow-hidden rounded-lg border border-line2 bg-panel p-1 shadow-xl">
              <div className="flex items-center gap-1.5 px-2 py-1 text-[10px] text-faint">
                <span className="rounded bg-violet-500/15 px-1.5 py-0.5 font-medium text-violet-700">/pair</span>
                双 AI · ↑↓ 选，回车确定
              </div>
              {PAIR_STYLES.map((s, i) => (
                <button
                  key={s.key}
                  onMouseEnter={() => setSlashIdx(i)}
                  onClick={() => triggerPair(s.key)}
                  className={`flex w-full items-center gap-2.5 rounded-md px-2 py-1.5 text-left ${i === slashIdx ? "bg-raised" : ""}`}
                >
                  {s.key === "debate" ? (
                    <Scales size={17} className="shrink-0 text-violet-600" />
                  ) : (
                    <Handshake size={17} className="shrink-0 text-teal-600" />
                  )}
                  <span className="flex min-w-0 flex-col">
                    <span className="text-[13px] font-medium text-ink">{s.label}</span>
                    <span className="truncate text-[11px] text-faint">{s.hint}</span>
                  </span>
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Property pills */}
        <div className="flex flex-wrap items-center gap-1.5 px-4 pb-3 pt-3">
          <Pill icon={<Robot size={14} />} label={`@${agentType}`} value={agentType} onChange={(v) => setAgentType(v as AgentType)} options={AGENTS.map((a) => ({ value: a, label: `@${a}` }))} />
          <Pill icon={<Stack size={14} />} label={groupTrigger} value={groupId} onChange={(v) => (v === "__new" ? onCreateGroup() : setGroupId(v))} options={[{ value: "", label: "无分组" }, ...groups.map((g) => ({ value: g.id, label: groupLabel(g) })), { value: "__new", label: "+ 新建分组" }]} />
          <Pill icon={<PriorityIcon p={priority} />} label={prioLabel} value={priority} onChange={(v) => setPriority(v as Priority)} options={PRIORITIES.map((p) => ({ value: p.key, label: p.label }))} />
          {labels.map((l) => (
            <button key={l} onClick={() => setLabels((ls) => ls.filter((x) => x !== l))} className="rounded-full bg-overlay px-2 py-1 text-[12px] text-ink hover:line-through" title="移除">
              {l}
            </button>
          ))}
          <LabelAdder onAdd={(l) => !labels.includes(l) && setLabels((ls) => [...ls, l])} />
        </div>

        {/* Footer */}
        <div className="flex items-center gap-3 border-t border-line px-4 py-2.5">
          <label className="ml-auto inline-flex cursor-pointer items-center gap-2 text-[12px] text-muted">
            <span>再建一个</span>
            <button type="button" onClick={() => setMore((v) => !v)} className={`relative h-4 w-7 rounded-full transition-colors ${more ? "bg-accent" : "bg-line2"}`} aria-pressed={more}>
              <span className={`absolute top-0.5 h-3 w-3 rounded-full bg-panel transition-all ${more ? "left-3.5" : "left-0.5"}`} />
            </button>
          </label>
          <button disabled={!body.trim() || busy} onClick={submit} className="inline-flex items-center gap-1.5 rounded-md bg-accent px-3.5 py-1.5 text-[13px] font-medium text-accent-fg transition-colors hover:bg-accent-hover disabled:opacity-40">
            <Plus size={14} weight="bold" /> 创建任务
          </button>
        </div>
      </div>
    </div>
  );
}
