import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import type { Task, Group, AgentType, Priority, ProjectView, TeamConfig } from "@harness/shared";
import { AGENT_TYPES, TEAM_DEFAULTS } from "@harness/shared";
import { X, ArrowsOut, ArrowsIn, Robot, Stack, Plus, Sparkle, Scales, CaretDown, Clock, Play, Tray, ArrowsClockwise, GitBranch, TreeStructure, UsersThree, Crown } from "@phosphor-icons/react";
import { api } from "./api";
import { PRIORITIES } from "./constants";
import { PriorityIcon, LabelAdder, RunLocation } from "./ui";
import { groupLabel } from "./util";
import { useEscape } from "./useEscape";
import { Menu, Pill } from "./Menu";
import { usePasteAttachments, AttachmentChips } from "./pasteAttachments";
import { ScheduleFields, toLocalInput } from "./ScheduleFields";
import { ExecutorPicker, type ExecutorSelection, useExecutorProfiles } from "./ExecutorPicker";

// 斜杠命令表。输入框里只剩一个 `/词` 时按前缀过滤它,列出的每一行都是一个**具体
// 动作**(`/pair` 是辩论,`/team` 是团队)。加命令只改这张表 ——
// 别再往下面写 `"pair".startsWith(...)` 那种硬编码。
type SlashAction =
  | { cmd: "pair"; kind: "pair"; label: string; hint: string; icon: ReactNode }
  | { cmd: "team"; kind: "team"; label: string; hint: string; icon: ReactNode };

const SLASH_COMMANDS: SlashAction[] = [
  { cmd: "pair", kind: "pair", label: "辩论", hint: "两个 AI 对抗，给你答案", icon: <Scales size={17} className="shrink-0 text-violet-600" /> },
  { cmd: "team", kind: "team", label: "团队", hint: "一个调度者带一队执行者，你随时插话", icon: <UsersThree size={17} className="shrink-0 text-accent" /> },
];


// 启动时机 (§9)：创建一个任务时「什么时候开始跑」。create=仅落 backlog；run=建完
// 立即跑（默认）；once/cron=挂定时，由调度器到点入队（不立即跑）。
type LaunchMode = "create" | "run" | "once" | "cron";
const LAUNCH_MODES: { key: LaunchMode; label: string; detail: string; icon: ReactNode; btn: string }[] = [
  { key: "create", label: "仅创建", detail: "进待办，手动再跑", icon: <Tray size={15} />, btn: "创建任务" },
  { key: "run", label: "创建并执行", detail: "立即开跑", icon: <Play size={15} weight="fill" />, btn: "创建并执行" },
  { key: "once", label: "一次性…", detail: "约定时间跑一次", icon: <Clock size={15} />, btn: "创建并定时" },
  { key: "cron", label: "循环…", detail: "按周期反复跑", icon: <ArrowsClockwise size={15} />, btn: "创建并定时" },
];

// New-task composer. No title field — the title is auto-generated by the first
// executing agent (user can edit later). 输入 `/` 唤起斜杠命令(见 SLASH_COMMANDS):
// `/pair` 交给辩论弹窗,`/team` 就地把这张单子切成「团队」模式。
export function CreateTask({
  project,
  groups,
  onClose,
  onCreated,
  onDebate,
  onCreateGroup,
  onOpenAgents,
}: {
  project: ProjectView;
  groups: Group[];
  onClose: () => void;
  onCreated: (t: Task) => void;
  onDebate: () => void;
  onCreateGroup: () => void;
  onOpenAgents?: () => void;
}) {
  const projectId = project.id;
  useEscape(onClose);
  const [body, setBody] = useState("");
  const [priority, setPriority] = useState<Priority>("none");
  const [executorPick, setExecutorPick] = useState<ExecutorSelection>({ agentType: "claude", executorId: null });
  const [groupId, setGroupId] = useState("");
  const [labels, setLabels] = useState<string[]>([]);
  const [more, setMore] = useState(false);
  const [expanded, setExpanded] = useState(false);
  const [busy, setBusy] = useState(false);
  const [launchMode, setLaunchMode] = useState<LaunchMode>("run"); // 默认：建完立即跑
  const [at, setAt] = useState(""); // datetime-local value (once)
  const [cron, setCron] = useState("0 9 * * *"); // 5-field expr (cron)
  const [slashIdx, setSlashIdx] = useState(0); // highlighted row in the slash-command picker
  // 团队模式(`/team`):不跳新弹窗,就地把这张单子改成「建一个常驻调度台」。
  // lead/worker 存的是**用户显式挑过的那个**,没挑就现算(见下面的 lead/worker) ——
  // 这样本机执行器的探测结果晚到也能把缺省补对,而用户挑过的永远不被覆盖。
  const [teamOn, setTeamOn] = useState(false);
  const [leadPick, setLeadPick] = useState<ExecutorSelection | null>(null);
  const [workerPick, setWorkerPick] = useState<ExecutorSelection | null>(null);
  const [detected, setDetected] = useState<{ type: AgentType; available: boolean; resident: boolean }[] | null>(null);
  const { profiles, providers } = useExecutorProfiles();

  // Per-task worktree opt-in. When on, the server creates <repo>/.worktrees/<id>
  // on a fresh `harness/<id8>` branch off the user-picked base before running.
  // Toggle is only meaningful for git projects; for non-repos we hide it.
  const [useWorktree, setUseWorktree] = useState(false);
  const [base, setBase] = useState(""); // empty = current HEAD
  const [branches, setBranches] = useState<string[]>([]);
  const [branchesLoaded, setBranchesLoaded] = useState(false);
  // Lazy-load branches the first time the toggle opens — non-repos still get an
  // empty list so the menu degrades gracefully.
  useEffect(() => {
    if (!useWorktree || branchesLoaded) return;
    let alive = true;
    api.projectBranches(project.id).then((r) => {
      if (!alive) return;
      setBranches(r.branches);
      if (!base && r.current) setBase(r.current);
      setBranchesLoaded(true);
    }).catch(() => alive && setBranchesLoaded(true));
    return () => { alive = false; };
  }, [useWorktree, branchesLoaded, project.id, base]);
  const objRef = useRef<HTMLTextAreaElement>(null);
  const { attachments, onPaste, remove, clear, error } = usePasteAttachments();

  // 只有切到团队模式才探测本机装了哪些 CLI(几个 which + --version,不值得每次开单子都跑)。
  useEffect(() => {
    if (!teamOn || detected) return;
    let alive = true;
    api.detectAgents().then(
      (d) => alive && setDetected(d),
      () => alive && setDetected([]),
    );
    return () => { alive = false; };
  }, [teamOn, detected]);

  // 「调度者」只能挑支持常驻会话的执行器(openResident,目前是 claude)—— 调度台要一个
  // 进程吃很多回合,不支持的 CLI 根本当不了。探测失败就退回内置缺省,别把下拉变空。
  const leadTypes = useMemo(() => {
    const ok = (detected ?? []).filter((d) => d.available && d.resident).map((d) => d.type);
    return ok.length ? ok : [TEAM_DEFAULTS.lead];
  }, [detected]);
  // 执行者不限类型(它们是普通一次性任务)。缺省挑一个跟调度者**不同**类型的本机执行器
  // —— 换个视角干活;都没有就跟调度者同类型。
  const workerTypes = useMemo(() => {
    const ok = (detected ?? []).filter((d) => d.available).map((d) => d.type);
    return ok.length ? ok : [...AGENT_TYPES];
  }, [detected]);
  const leadSelection = leadPick && leadTypes.includes(leadPick.agentType) ? leadPick : { agentType: leadTypes[0]!, executorId: null };
  const workerSelection =
    workerPick && workerTypes.includes(workerPick.agentType)
      ? workerPick
      : { agentType: workerTypes.find((t) => t !== leadSelection.agentType) ?? leadSelection.agentType, executorId: null };
  const lead = leadSelection.agentType;
  const worker = workerSelection.agentType;

  // Slash command: when the input is just a "/word" token, list the matching
  // commands right under the text (↑↓ to move, Enter/click to choose).
  const slashMatch = /^\s*\/(\w*)$/.exec(body);
  const slashHits = slashMatch ? SLASH_COMMANDS.filter((c) => c.cmd.startsWith((slashMatch[1] ?? "").toLowerCase())) : [];
  const slashOpen = slashHits.length > 0;
  const slashSel = Math.min(slashIdx, Math.max(0, slashHits.length - 1));

  const pickSlash = (a: SlashAction) => {
    setBody("");
    setSlashIdx(0);
    if (a.kind === "pair") onDebate();
    else setTeamOn(true); // 团队任务就在这张单子上建,不换弹窗
    objRef.current?.focus();
  };

  const submit = async () => {
    const obj = body.trim();
    if ((!obj && !attachments.length) || busy) return;
    if (slashOpen) {
      pickSlash(slashHits[slashSel]!);
      return;
    }
    if (/^\/pair\b/i.test(obj)) {
      pickSlash(SLASH_COMMANDS[0]!);
      return;
    }
    if (/^\/team\b/i.test(obj)) {
      pickSlash(SLASH_COMMANDS[SLASH_COMMANDS.length - 1]!);
      return;
    }
    // A timed mode needs its time/expr (guards the ⌘↵ path, which skips the button).
    if ((launchMode === "once" && !at) || (launchMode === "cron" && !cron.trim())) return;
    setBusy(true);
    try {
      const provisionalTitle = obj.split("\n")[0].slice(0, 30) || "未命名任务";
      const team: TeamConfig = {
        lead,
        worker,
        leadExecutorId: leadSelection.executorId,
        workerExecutorId: workerSelection.executorId,
      };
      const t = await api.createTask({
        projectId,
        title: provisionalTitle,
        body: obj,
        attachments: attachments.map((a) => a.path),
        mode: teamOn ? "team" : "single",
        // 团队任务的执行器由 team.lead 决定;agentType 跟着填一份,好让只认这个字段的
        // 列表/徽标显示对。
        agentType: teamOn ? lead : executorPick.agentType,
        executorId: teamOn ? null : executorPick.executorId,
        ...(teamOn ? { team } : {}),
        priority,
        labels,
        // 调度台不走「首个 agent 自动起名」那套协议(它是常驻会话,没有那个回合),
        // 标题先取第一行,用户在调度台 header 上随时改。
        autoTitle: !teamOn,
        // 团队模式不给调度台开 worktree:执行者是各自独立的任务、跑在项目目录,
        // 只把调度者挪进 worktree 只会让两边看到不同的文件。隔离在派活时逐个开。
        useWorktree: project.health.isRepo && !teamOn ? useWorktree : false,
        worktreeBase: !teamOn && useWorktree && base ? base : null,
      });
      // 启动时机：run=立即跑；once/cron=挂定时（调度器到点入队，不在此刻跑）；
      // create=什么都不做（任务停在 backlog，手动再运行）。
      if (launchMode === "run") await api.runTask(t.id);
      else if (launchMode === "once") await api.setSchedule(t.id, { kind: "once", at: new Date(at).toISOString() });
      else if (launchMode === "cron") await api.setSchedule(t.id, { kind: "cron", cron: cron.trim() });
      onCreated(t);
      if (more) {
        setBody("");
        setLabels([]);
        clear();
        objRef.current?.focus();
      } else {
        onClose();
      }
    } finally {
      setBusy(false);
    }
  };

  const selectedGroup = groups.find((g) => g.id === groupId);
  const groupTrigger = selectedGroup ? groupLabel(selectedGroup) : "分组";
  const prioLabel = priority === "none" ? "优先级" : PRIORITIES.find((p) => p.key === priority)!.label;

  const active = LAUNCH_MODES.find((m) => m.key === launchMode)!;
  // The exact derived branch (`harness/<id8>`) is only known after the server
  // mints the task id — show a generic preview so the user knows the format.
  const taskIdPreview = "harness/<id8>";
  // A scheduled mode needs a valid time/expr before it can submit.
  const schedInvalid = (launchMode === "once" && !at) || (launchMode === "cron" && !cron.trim());
  const canSubmit = (!!body.trim() || attachments.length > 0) && !busy && !schedInvalid;
  const pickMode = (m: LaunchMode) => {
    if (m === "once" && !at) setAt(toLocalInput(new Date(Date.now() + 3600_000).toISOString())); // 默认 +1h
    setLaunchMode(m);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center bg-black/30 pt-[12vh]" onClick={onClose}>
      <div
        className={`flex flex-col overflow-visible rounded-xl border border-line2 bg-panel shadow-2xl transition-all ${
          expanded ? "h-[78vh] w-[920px]" : "w-[640px]"
        } max-w-[94vw]`}
        onClick={(e) => e.stopPropagation()}
        onKeyDown={(e) => {
          if ((e.metaKey || e.ctrlKey) && e.key === "Enter") {
            e.preventDefault();
            submit();
          }
        }}
      >
        {/* Header / breadcrumb */}
        <div className="flex items-center gap-2 px-4 pt-3.5">
          <span className="inline-flex items-center gap-1.5 rounded-md bg-raised px-1.5 py-0.5 text-[12px] font-medium text-ink">
            <span className="grid h-4 w-4 place-items-center rounded bg-accent text-[9px] font-semibold text-accent-fg">
              {project.name.slice(0, 1).toUpperCase()}
            </span>
            {project.name}
          </span>
          <span className="text-faint">›</span>
          <span className="text-[13px] font-medium text-muted">新建任务</span>
          {teamOn && (
            <button
              onClick={() => setTeamOn(false)}
              className="group inline-flex items-center gap-1 rounded-md bg-accent/10 px-1.5 py-0.5 text-[12px] font-medium text-accent transition-colors hover:bg-accent/15"
              title="退出团队模式（改回单个 agent）"
            >
              <UsersThree size={13} weight="fill" />
              团队
              <X size={11} weight="bold" className="text-accent/50 group-hover:text-accent" />
            </button>
          )}

          <div className="ml-auto flex items-center gap-1">
            <button onClick={() => setExpanded((v) => !v)} className="grid h-7 w-7 place-items-center rounded-md text-muted hover:bg-raised hover:text-ink" title={expanded ? "收起" : "展开"}>
              {expanded ? <ArrowsIn size={15} /> : <ArrowsOut size={15} />}
            </button>
            <button onClick={onClose} className="grid h-7 w-7 place-items-center rounded-md text-muted hover:bg-raised hover:text-ink" title="关闭 Esc">
              <X size={16} />
            </button>
          </div>
        </div>
        {/* Run location — agents run in this dir (or a temp dir if it's missing) */}
        <div className="px-4 pt-1.5">
          <RunLocation project={project} />
        </div>
        {project.health.isRepo && !teamOn && (
          <WorktreeField
            taskIdPreview={taskIdPreview}
            on={useWorktree}
            base={base}
            branches={branches}
            onToggle={() => setUseWorktree((v) => !v)}
            onBase={setBase}
          />
        )}

        {/* Objective (no title field — AI titles it) */}
        <div className={`relative flex min-h-0 flex-col px-4 pt-3 ${expanded ? "flex-1" : ""}`}>
          <textarea
            ref={objRef}
            autoFocus
            value={body}
            onChange={(e) => setBody(e.target.value)}
            onPaste={onPaste}
            onKeyDown={(e) => {
              if (slashOpen) {
                if (e.key === "ArrowDown") {
                  e.preventDefault();
                  setSlashIdx(Math.min(slashHits.length - 1, slashSel + 1));
                } else if (e.key === "ArrowUp") {
                  e.preventDefault();
                  setSlashIdx(Math.max(0, slashSel - 1));
                } else if (e.key === "Enter") {
                  e.preventDefault();
                  pickSlash(slashHits[slashSel]!);
                }
              }
            }}
            placeholder={
              teamOn
                ? "给调度者的目标…（它会自己拆活、派执行者、有问题问你）"
                : "描述要做什么 / 给 agent 的目标…（输入 / 唤起命令：/pair 双 AI 辩论，/team 一队）"
            }
            className={`resize-none bg-transparent text-[15px] leading-relaxed text-ink outline-none placeholder:text-faint ${
              expanded ? "flex-1" : "min-h-[88px]"
            }`}
          />
          <div className="flex items-center gap-1 pb-1 text-[11px] text-faint">
            {teamOn ? (
              <>
                <UsersThree size={12} weight="fill" className="text-accent/70" />
                调度者常驻不断线：随时插话改方向；标题先取第一行，之后在调度台上改
              </>
            ) : (
              <>
                <Sparkle size={12} weight="fill" className="text-accent/70" />
                标题将由首个执行的 agent 自动生成，可随后修改
              </>
            )}
          </div>
          <AttachmentChips attachments={attachments} onRemove={remove} error={error} />

          {slashOpen && (
            <div className="absolute left-4 top-9 z-10 w-80 overflow-hidden rounded-lg border border-line2 bg-panel p-1 shadow-xl">
              <div className="px-2 py-1 text-[10px] text-faint">命令 · ↑↓ 选，回车确定</div>
              {slashHits.map((s, i) => (
                <button
                  key={`${s.cmd}:${s.label}`}
                  onMouseEnter={() => setSlashIdx(i)}
                  onClick={() => pickSlash(s)}
                  className={`flex w-full items-center gap-2.5 rounded-md px-2 py-1.5 text-left ${i === slashSel ? "bg-raised" : ""}`}
                >
                  {s.icon}
                  <span className="flex min-w-0 flex-col">
                    <span className="text-[13px] font-medium text-ink">{s.label}</span>
                    <span className="truncate text-[11px] text-faint">{s.hint}</span>
                  </span>
                  <span className="ml-auto shrink-0 rounded bg-raised px-1.5 py-0.5 text-[10px] text-muted">/{s.cmd}</span>
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Property pills */}
        <div className="flex flex-wrap items-center gap-1.5 px-4 pb-3 pt-3">
          {teamOn ? (
            <>
              <ExecutorPicker
                icon={<Crown size={14} />}
                selection={leadSelection}
                onSelect={setLeadPick}
                profiles={profiles}
                providers={providers}
                types={leadTypes}
                label={`调度者 ${profiles.find((a) => a.id === leadSelection.executorId)?.name ?? `默认 ${lead}`}`}
                includeManage={!!onOpenAgents}
                onOpenAgents={onOpenAgents}
                menuWidth={320}
              />
              <ExecutorPicker
                icon={<Robot size={14} />}
                selection={workerSelection}
                onSelect={setWorkerPick}
                profiles={profiles}
                providers={providers}
                types={workerTypes}
                label={`执行者 ${profiles.find((a) => a.id === workerSelection.executorId)?.name ?? `默认 ${worker}`}`}
                includeManage={!!onOpenAgents}
                onOpenAgents={onOpenAgents}
                menuWidth={320}
              />
            </>
          ) : (
            <ExecutorPicker
              icon={<Robot size={14} />}
              selection={executorPick}
              onSelect={setExecutorPick}
              profiles={profiles}
              providers={providers}
              types={[...AGENT_TYPES]}
              includeManage={!!onOpenAgents}
              onOpenAgents={onOpenAgents}
              menuWidth={320}
            />
          )}

          <Pill icon={<Stack size={14} />} label={groupTrigger} value={groupId} onChange={(v) => (v === "__new" ? onCreateGroup() : setGroupId(v))} options={[{ value: "", label: "无分组" }, ...groups.map((g) => ({ value: g.id, label: groupLabel(g) })), { value: "__new", label: "+ 新建分组" }]} />
          <Pill icon={<PriorityIcon p={priority} />} label={prioLabel} value={priority} onChange={(v) => setPriority(v as Priority)} options={PRIORITIES.map((p) => ({ value: p.key, label: p.label }))} />
          {labels.map((l) => (
            <button key={l} onClick={() => setLabels((ls) => ls.filter((x) => x !== l))} className="rounded-full bg-overlay px-2 py-1 text-[12px] text-ink hover:line-through" title="移除">
              {l}
            </button>
          ))}
          <LabelAdder onAdd={(l) => !labels.includes(l) && setLabels((ls) => [...ls, l])} />
        </div>

        {/* Schedule strip — slides in only for the timed modes (once / cron) */}
        {(launchMode === "once" || launchMode === "cron") && (
          <div className="flex flex-wrap items-center gap-2 border-t border-line px-4 py-2.5 text-[12px]">
            <span className="inline-flex items-center gap-1.5 text-faint">
              {launchMode === "once" ? <Clock size={13} /> : <ArrowsClockwise size={13} />}
              {launchMode === "once" ? "一次性" : "循环"}
            </span>
            <ScheduleFields kind={launchMode} at={at} cron={cron} onAt={setAt} onCron={setCron} />
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center gap-3 border-t border-line px-4 py-2.5">
          <label className="ml-auto inline-flex cursor-pointer items-center gap-2 text-[12px] text-muted">
            <span>再建一个</span>
            <button type="button" onClick={() => setMore((v) => !v)} className={`relative h-4 w-7 rounded-full transition-colors ${more ? "bg-accent" : "bg-line2"}`} aria-pressed={more}>
              <span className={`absolute top-0.5 h-3 w-3 rounded-full bg-panel transition-all ${more ? "left-3.5" : "left-0.5"}`} />
            </button>
          </label>
          <div className="inline-flex items-stretch overflow-hidden rounded-md">
            <button disabled={!canSubmit} onClick={submit} className="inline-flex items-center gap-1.5 bg-accent px-3.5 py-1.5 text-[13px] font-medium text-accent-fg transition-colors hover:bg-accent-hover disabled:opacity-40">
              <Plus size={14} weight="bold" /> {active.btn}
            </button>
            <Menu
              value={launchMode}
              onChange={(v) => pickMode(v as LaunchMode)}
              options={LAUNCH_MODES.map((m) => ({ value: m.key, label: m.label, icon: m.icon, detail: m.detail }))}
              align="right"
              menuWidth={232}
              triggerClassName="grid place-items-center border-l border-accent-fg/20 bg-accent px-1.5 text-accent-fg transition-colors hover:bg-accent-hover"
            >
              <CaretDown size={13} weight="bold" />
            </Menu>
          </div>
        </div>
      </div>
    </div>
  );
}

// 「在新 worktree 里跑」开关 + base 分支选择。和 RunLocation 同一视觉层，让用户
// 一眼看清「这次任务跑在哪、用哪个分支」。关闭时只占一行；开启时展开一个紧凑的
// base 选择面板（沿用 Pill / Menu 风格，和正文 Pill 一致）。
function WorktreeField({
  on,
  base,
  branches,
  taskIdPreview,
  onToggle,
  onBase,
}: {
  on: boolean;
  base: string;
  branches: string[];
  taskIdPreview: string;
  onToggle: () => void;
  onBase: (b: string) => void;
}) {
  const baseLabel = base || "当前分支";
  return (
    <div className="px-4 pt-1">
      <button
        type="button"
        onClick={onToggle}
        className="inline-flex items-center gap-1.5 rounded-md px-1.5 py-0.5 text-[11px] text-muted hover:bg-raised hover:text-ink"
        title={on ? "关闭：直接在项目目录跑" : "开启：本次任务在新 worktree 里跑"}
      >
        <TreeStructure size={12} className={on ? "text-accent" : "text-faint"} />
        <span>用 worktree 隔离</span>
        <span
          className={`relative ml-0.5 inline-block h-3 w-5 rounded-full transition-colors ${on ? "bg-accent" : "bg-line2"}`}
          aria-pressed={on}
        >
          <span className={`absolute top-0.5 h-2 w-2 rounded-full bg-panel transition-all ${on ? "left-2.5" : "left-0.5"}`} />
        </span>
      </button>
      {on && (
        <div className="ml-1 mt-1 flex flex-wrap items-center gap-1.5 text-[11px] text-muted">
          <span className="text-faint">base</span>
          <Pill
            icon={<GitBranch size={11} />}
            label={baseLabel}
            value={base}
            onChange={onBase}
            options={[
              { value: "", label: "当前分支（HEAD）" },
              ...branches.map((b) => ({ value: b, label: b })),
            ]}
            menuWidth={220}
          />
          <span className="text-faint">→ 新分支 {taskIdPreview}</span>
        </div>
      )}
    </div>
  );
}
